# 使用されているビルド使用スタンダートのバージョン0.2が最新
version: 0.2

# phasesにはあとinstallがある
phases:
  pre_build:
    commands:
      - echo "ECRへログイン"
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - echo "DockerHubにログイン"
      - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  build:
    commands:
      - echo "ビルド開始"
      - docker build -f ./backend_app/Dockerfile -t ${REPOSITORY_URI}:test ./backend_app
  post_build:
    commands:
      - echo "ECRへpush"
      - docker push "${REPOSITORY_URI}:test"
      - printf '{"Version":"1.0","ImageURI":"%s"}' ${REPOSITORY_URI}:test > imageDetail.json
      - echo "タスク定義を書き換える"
      - pwd
      - sed -ie "s#<TASK_FAMILY>#${TASK_FAMILY}#" taskdef.json
      - sed -ie "s#<TASK_EXECUTION_ROLE_ARN>#${TASK_EXECUTION_ROLE_ARN}#" taskdef.json
      - sed -ie "s#<SECRETS_FOR_DB_ARN>#${SECRETS_FOR_DB_ARN}#" taskdef.json
      - sed -ie "s#<REGION>#${REGION}#" taskdef.json
      - sed -ie "s#<LOG_GROUP_NAME>#${LOG_GROUP_NAME}#" taskdef.json
      - echo "$(cat taskdef.json)"
artifacts:
  files:
    - imageDetail.json